# require(missMDA)

data(vnf, package = "missMDA")
p = ncol(vnf)
cand.edges = as.list(data.frame(combn(p, 2)))
dp = doublep(vnf, cand.edges)
plot(dp)
EFI = efi(vnf, dp)
names(vnf)
lapply(vnf, levels)
summary(vnf)
estimate(EFI, "(Q7.1 == 1) & (Q40.3 == 2)")

data(TitanicNA, package = "missMDA")
p = ncol(TitanicNA)
cand.edges = as.list(data.frame(combn(p, 2)))
dp = doublep(TitanicNA, cand.edges)
plot(dp)
EFI = efi(TitanicNA, dp)
names(TitanicNA)
lapply(TitanicNA, levels)
summary(TitanicNA)
estimate(EFI, "(CLASS == 1) & (SEX == 0)")
