# require(missMDA)

data(vnf, package = "missMDA"); p = ncol(vnf)
edges_list <- construct_tree(p)
dp = doublep(vnf, edges_list)
plot(dp)
EFI = efi(vnf, dp)
names(vnf)
lapply(vnf, levels)
summary(vnf)
estimate(EFI, "(Q7.1 == 1) & (Q40.3 == 2)")

data(TitanicNA, package = "missMDA")
p = ncol(TitanicNA)
edges_list <- construct_tree(p)
dp = doublep(TitanicNA, edges_list)
plot(dp)
EFI = efi(TitanicNA, dp)
names(TitanicNA)
lapply(TitanicNA, levels)
summary(TitanicNA)
estimate(EFI, "(CLASS == 1) & (SEX == 0)")
